### ISSUE TITLE
how to extract alignment file from poppunk

### ISSUE THREAD

**Issue by asangphukieo** [bacpop/PopPIPE#1]
Hi John,
I would like to build ML tree with IQ tree, but it requires an align_variants.aln.
How can I export the alignment file from Poppunk output.

Thank you,
Apiwat

**Comment by johnlees** [comment]
This should be produced by [ska](https://github.com/simonrharris/SKA), which will take the assemblies as input. PopPUNK itself is alignment-free
If you run this pipeline with snakemake it should be automated - but please not this is still experimental. You will need to change at least the following lines in the snakefile:
https://github.com/johnlees/PopPIPE/blob/master/Snakefile#L87-L92
https://github.com/johnlees/PopPIPE/blob/master/Snakefile#L233-L242

**Comment by asangphukieo** [comment]
Thank you John, I will go for the ska first. 

Just curious, in case of running the whole pipeline, it requires poppunk database file in ".h5" format, but I don't see it from poppunk result. How to generate this file?

Thanks a lot,
Apiwat

**Comment by johnlees** [comment]
Are you using PopPUNK v2 (with pp-sketchlib >=v1.3.0), which generates a .h5 rather than .msh files? You'll need to for this pipeline to work

**Comment by asangphukieo** [comment]
Yes, I currently used PopPUNK v1. I will try version 2. 
Thank you
