### ISSUE TITLE
Command for installing dependencies manually

### ISSUE THREAD

**Issue by HarryHung** [bacpop/PopPIPE#8]
Currently the suggested command is 
`conda create -n poppipe --file=environment.yml`

but this command will lead to 
`CondaValueError: could not parse 'name: pp_env' in: environment.yml`

I would suggest the correct command should be: 
`conda env create -n poppipe --file=environment.yml`

If you agree, the same command in the `README` of this repo and `PopPUNK/docs/subclustering.rst` will both need to be updated.

**Comment by johnlees** [comment]
Thanks Harry, I'll update those now!
